scrlayout/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/trailers'

  get 'pages/funny'

  get 'pages/cricket'

end

scrlayout/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

scrlayout/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

scrlayout/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

scrlayout/app/helpers/application_helper.rb
module ApplicationHelper
end

scrlayout/app/helpers/home_helper.rb
module HomeHelper
end

scrlayout/app/helpers/pages_helper.rb
module PagesHelper
end

scrlayout/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scrlayout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.2/js/materialize.min.js"></script>
          
</head>
<body>
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper #b71c1c red darken-4">
        <a href="<%= pages_home_path %>" class="brand-logo">Here U Wish</a>
        <ul class="right hide-on-med-and-down">
          <li><a href="<%= pages_home_path %>">Home</a></li>
          <li><a href="<%= pages_trailers_path %>">Trailers</a></li>
          <li><a href="<%= pages_funny_path %>">Funny</a></li>
          <li><a href="<%= pages_cricket_path %>">Cricket</a></li>
        </ul>
    </div>
  </nav>
</div>
  <div class="row #424242 grey darken-3">
  	<div class="col s12 m8 l9">
  		<%= yield %>
  	</div>
  </div>
<footer class="page-footer #b71c1c red darken-4">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Here U Wish</h5>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="<%= pages_home_path %>">Home</a></li>
                  <li><a class="grey-text text-lighten-3" href="<%= pages_trailers_path %>">Trailers</a></li>
                  <li><a class="grey-text text-lighten-3" href="<%= pages_funny_path %>">Funny</a></li>
                  <li><a class="grey-text text-lighten-3" href="<%= pages_cricket_path %>">Cricket</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2015 Copyright Text
            </div>
          </div>
        </footer>
</body>
</html>

scrlayout/app/views/pages/cricket.html.erb
<h1>cricket Videos</h1>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>

scrlayout/app/views/pages/funny.html.erb
<h1>Funny Videos</h1>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>

scrlayout/app/views/pages/home.html.erb
<div class="row">
    <div class="col s4">
    	<h3>Trailers</h3>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    </div>
    <div class="col s4">
    	<h3>Funny</h3>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    </div>
   	<div class="col s4">
   		<h3>Cricket</h3>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    <video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
    </div>
</div>

scrlayout/app/views/pages/trailers.html.erb
<h1>Latest Trailers</h1>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>
<video src="https://www.youtube.com/watch?v=GCvipxfEnJY" controls></video>